services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: notionlock
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: notionlock_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass devpassword
    ports:
      - "6379:6379"

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - ../backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      PORT: 3001
      DATABASE_URL: postgresql://notionlock:devpassword@postgres:5432/notionlock_dev
      REDIS_URL: redis://:devpassword@redis:6379
      JWT_SECRET: dev-secret-key
      FRONTEND_URL: http://localhost:3000
      SMTP_HOST: sandbox.smtp.mailtrap.io
      SMTP_PORT: 2525
      SMTP_USER: 2488d56b8aed67
      SMTP_PASS: 366d9c26d4b2d4
      FROM_EMAIL: noreply@notionlock.com
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    command: npm run dev

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    command: npm start

volumes:
  postgres-dev-data:
